# Generated by Django 4.0.4 on 2022-05-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_todo_options_alter_todo_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('position',)},
        ),
    ]
